providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "23"

[phases.setup]
nixPkgs = ["nodejs_23"]

[phases.build]
cmds = ["npm install", "npm run build"]

[phases.start]
cmds = ["npm run start"]
